AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: OpenTelemetry Python Lambda layer for Python 3.8 Runtime
Resources:
  layer:
    Type: AWSUtility::CloudFormation::CommandRunner
    Properties:
      Command:
        Fn::Sub: '../layerArn.sh'
  api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      TracingEnabled: true
      OpenApiVersion: 3.0.2
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./function
      Description: OTel Python Lambda dry Sample
      MemorySize: 512
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
      Tracing: Active
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/python/otel-instrument
      Layers:
        - Fn::GetAtt: layer.Output
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref api
            Path: /
            Method: GET